/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Sandeep
 */
public class home extends javax.swing.JFrame {
    
    public int z = 0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
//        jManuButton.setVisible(false); (first mistake)
        jNewBuyerButton.setVisible(false);
        jUpdateBuyerButton.setVisible(false);
        jBuyerDetailsButton.setVisible(false);
        jDeleteBuyerButton.setVisible(false);
        jNewBookButton.setVisible(false);
        jUpdateBookButton.setVisible(false);
        jBookDetails.setVisible(false);
        jRemoveBookButton.setVisible(false);
        jBillingButton.setVisible(false);
        jLogoutButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jUpdateBuyerButton = new javax.swing.JButton();
        jBuyerDetailsButton = new javax.swing.JButton();
        jDeleteBuyerButton = new javax.swing.JButton();
        jNewBookButton = new javax.swing.JButton();
        jUpdateBookButton = new javax.swing.JButton();
        jBookDetails = new javax.swing.JButton();
        jRemoveBookButton = new javax.swing.JButton();
        jBillingButton = new javax.swing.JButton();
        jLogoutButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jNewBuyerButton = new javax.swing.JButton();
        jManuButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 20, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("  Welcome, User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 200, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Billing Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 70));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUpdateBuyerButton.setBackground(new java.awt.Color(0, 0, 0));
        jUpdateBuyerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUpdateBuyerButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/update.png"))); // NOI18N
        jUpdateBuyerButton.setText("Update Buyer");
        jUpdateBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jUpdateBuyerButtonComponentShown(evt);
            }
        });
        jUpdateBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBuyerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, -1));

        jBuyerDetailsButton.setBackground(new java.awt.Color(0, 0, 0));
        jBuyerDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBuyerDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        jBuyerDetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/detail.png"))); // NOI18N
        jBuyerDetailsButton.setText("Buyer Details");
        jBuyerDetailsButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBuyerDetailsButtonComponentShown(evt);
            }
        });
        jBuyerDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuyerDetailsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jBuyerDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, -1));

        jDeleteBuyerButton.setBackground(new java.awt.Color(0, 0, 0));
        jDeleteBuyerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jDeleteBuyerButton.setForeground(new java.awt.Color(255, 255, 255));
        jDeleteBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/delete.png"))); // NOI18N
        jDeleteBuyerButton.setText("Delete Buyer");
        jDeleteBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDeleteBuyerButtonComponentShown(evt);
            }
        });
        jDeleteBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBuyerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, -1));

        jNewBookButton.setBackground(new java.awt.Color(0, 0, 0));
        jNewBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNewBookButton.setForeground(new java.awt.Color(255, 255, 255));
        jNewBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/newBook.png"))); // NOI18N
        jNewBookButton.setText("New Book");
        jNewBookButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jNewBookButtonComponentShown(evt);
            }
        });
        jNewBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewBookButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jNewBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, -1));

        jUpdateBookButton.setBackground(new java.awt.Color(0, 0, 0));
        jUpdateBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jUpdateBookButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/update.png"))); // NOI18N
        jUpdateBookButton.setText("Update Book");
        jUpdateBookButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jUpdateBookButtonComponentShown(evt);
            }
        });
        jUpdateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBookButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, -1));

        jBookDetails.setBackground(new java.awt.Color(0, 0, 0));
        jBookDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBookDetails.setForeground(new java.awt.Color(255, 255, 255));
        jBookDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/detail.png"))); // NOI18N
        jBookDetails.setText("Book Details");
        jBookDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBookDetailsComponentShown(evt);
            }
        });
        jBookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(jBookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 150, -1));

        jRemoveBookButton.setBackground(new java.awt.Color(0, 0, 0));
        jRemoveBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRemoveBookButton.setForeground(new java.awt.Color(255, 255, 255));
        jRemoveBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/delete.png"))); // NOI18N
        jRemoveBookButton.setText("Remove Book");
        jRemoveBookButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jRemoveBookButtonComponentShown(evt);
            }
        });
        jRemoveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveBookButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jRemoveBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 150, -1));

        jBillingButton.setBackground(new java.awt.Color(0, 0, 0));
        jBillingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBillingButton.setForeground(new java.awt.Color(255, 255, 255));
        jBillingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/billing.png"))); // NOI18N
        jBillingButton.setText("Billing");
        jBillingButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBillingButtonComponentShown(evt);
            }
        });
        jBillingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBillingButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jBillingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 150, -1));

        jLogoutButton.setBackground(new java.awt.Color(255, 0, 0));
        jLogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        jLogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/logout.png"))); // NOI18N
        jLogoutButton.setText("Logout");
        jLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 150, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 10));

        jNewBuyerButton.setBackground(new java.awt.Color(0, 0, 0));
        jNewBuyerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNewBuyerButton.setForeground(new java.awt.Color(255, 255, 255));
        jNewBuyerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/newBuyer.png"))); // NOI18N
        jNewBuyerButton.setText("New Buyer");
        jNewBuyerButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jNewBuyerButtonComponentShown(evt);
            }
        });
        jNewBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewBuyerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jNewBuyerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        jManuButton.setBackground(new java.awt.Color(102, 102, 255));
        jManuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jManuButton.setForeground(new java.awt.Color(255, 255, 255));
        jManuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A New icon/manu.png"))); // NOI18N
        jManuButton.setText(" Manu");
        jManuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jManuButtonMouseClicked(evt);
            }
        });
        jPanel2.add(jManuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/closeButton_icon.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 660));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/library-3.png.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 750, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 1030, 660));

        setSize(new java.awt.Dimension(1366, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutButtonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout", "Selete", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jLogoutButtonActionPerformed

    private void jManuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jManuButtonMouseClicked
        // TODO add your handling code here:
        if(z==0){
            try{
                Thread.sleep(100);
                jNewBuyerButton.setVisible(true);
            }
            catch(Exception e){
                
            }
        }
        else{
//            jManuButton.setVisible(false); (connected to first mistake)
            jNewBuyerButton.setVisible(false);
            jUpdateBuyerButton.setVisible(false);
            jBuyerDetailsButton.setVisible(false);
            jDeleteBuyerButton.setVisible(false);
            jNewBookButton.setVisible(false);
            jUpdateBookButton.setVisible(false);
            jBookDetails.setVisible(false);
            jRemoveBookButton.setVisible(false);
            jBillingButton.setVisible(false);
            jLogoutButton.setVisible(false);
            z = 0;
        }
    }//GEN-LAST:event_jManuButtonMouseClicked

    private void jNewBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jNewBuyerButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jUpdateBuyerButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jNewBuyerButtonComponentShown

    private void jUpdateBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jUpdateBuyerButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jBuyerDetailsButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jUpdateBuyerButtonComponentShown

    private void jBuyerDetailsButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBuyerDetailsButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jDeleteBuyerButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jBuyerDetailsButtonComponentShown

    private void jDeleteBuyerButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDeleteBuyerButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jNewBookButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jDeleteBuyerButtonComponentShown

    private void jNewBookButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jNewBookButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jUpdateBookButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jNewBookButtonComponentShown

    private void jUpdateBookButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jUpdateBookButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jBookDetails.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jUpdateBookButtonComponentShown

    private void jBookDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBookDetailsComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jRemoveBookButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jBookDetailsComponentShown

    private void jRemoveBookButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jRemoveBookButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jBillingButton.setVisible(true);
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jRemoveBookButtonComponentShown

    private void jBillingButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBillingButtonComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(50);
                jLogoutButton.setVisible(true);
                z = 1;
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_jBillingButtonComponentShown

    private void jNewBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewBuyerButtonActionPerformed
        // TODO add your handling code here:
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_jNewBuyerButtonActionPerformed

    private void jUpdateBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBuyerButtonActionPerformed
        // TODO add your handling code here:
        new updateBuyer().setVisible(true);
    }//GEN-LAST:event_jUpdateBuyerButtonActionPerformed

    private void jBuyerDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuyerDetailsButtonActionPerformed
        // buyer details button action performed...
        new buyerDetails().setVisible(true);
    }//GEN-LAST:event_jBuyerDetailsButtonActionPerformed

    private void jDeleteBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBuyerButtonActionPerformed
        // delete buyer from data...
        new deleteBuyer().setVisible(true);
    }//GEN-LAST:event_jDeleteBuyerButtonActionPerformed

    private void jNewBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewBookButtonActionPerformed
        // new book button Action performed for getting new book window..
        new newBook().setVisible(true);
    }//GEN-LAST:event_jNewBookButtonActionPerformed

    private void jBookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookDetailsActionPerformed
        // to see books details action performed to reach bookDetails window..
        new bookDetails().setVisible(true);
    }//GEN-LAST:event_jBookDetailsActionPerformed

    private void jUpdateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBookButtonActionPerformed
        // to update book details action performed to reach updateBook window..
        new updateBook().setVisible(true);
    }//GEN-LAST:event_jUpdateBookButtonActionPerformed

    private void jRemoveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveBookButtonActionPerformed
        // removeBook window action performed to reach removeBook window..
        new removeBook().setVisible(true);
    }//GEN-LAST:event_jRemoveBookButtonActionPerformed

    private void jBillingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBillingButtonActionPerformed
        // billing window action performed..
        new billing().setVisible(true);
    }//GEN-LAST:event_jBillingButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Close button action performed.... to close the application.
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBillingButton;
    private javax.swing.JButton jBookDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jBuyerDetailsButton;
    private javax.swing.JButton jDeleteBuyerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLogoutButton;
    private javax.swing.JButton jManuButton;
    private javax.swing.JButton jNewBookButton;
    private javax.swing.JButton jNewBuyerButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jRemoveBookButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jUpdateBookButton;
    private javax.swing.JButton jUpdateBuyerButton;
    // End of variables declaration//GEN-END:variables
}
